#!/bin/bash
export PGUSER=postgres

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "hmc" <<-EOSQL

-- Backend
CREATE USER "${BACKEND_USER}"
    NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT
    ENCRYPTED PASSWORD '${BACKEND_PASSWORD}';
GRANT CONNECT ON DATABASE hmc TO "${BACKEND_USER}";
GRANT USAGE ON SCHEMA public TO "${BACKEND_USER}";
GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public
    TO "${BACKEND_USER}";

-- Grafana
CREATE USER "${GRAFANA_USER}"
    NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT
    ENCRYPTED PASSWORD '${GRAFANA_PASSWORD}';
GRANT CONNECT ON DATABASE hmc TO "${GRAFANA_USER}";
GRANT USAGE ON SCHEMA public TO "${GRAFANA_USER}";
GRANT SELECT
    ON ALL TABLES IN SCHEMA public
    TO "${GRAFANA_USER}";

EOSQL
