FROM rust:1.88

ARG target=x86_64-unknown-linux-gnu

RUN cargo install cargo-watch

ENV CARGO_TARGET_DIR=/build
VOLUME [ "/mount/repository" ]
WORKDIR /mount/repository
EXPOSE 24316

ENTRYPOINT [ \
    "cargo", "watch", "--why", "--delay", "1.5", \
    "-x", "'build -p backend'", \
    "--watch", "./Cargo.toml", \
    "--watch", "crates/backend/src", \
    "--watch", "crates/backend/Cargo.toml", \
    "--", "cargo", "run", "--bin", "backend", \
    "--", "--port", "24316" \
    ]
